//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogicSimulator.WindowsUI.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter equation.
        /// </summary>
        internal static string EquationDialog_Label {
            get {
                return ResourceManager.GetString("EquationDialog_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equation.
        /// </summary>
        internal static string EquationDialog_Name {
            get {
                return ResourceManager.GetString("EquationDialog_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to show.
        /// </summary>
        internal static string Error_EmptyScheme {
            get {
                return ResourceManager.GetString("Error_EmptyScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot export to HTML.
        /// </summary>
        internal static string Error_HtmlExport {
            get {
                return ResourceManager.GetString("Error_HtmlExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheme is invalid!.
        /// </summary>
        internal static string Error_InvalidScheme {
            get {
                return ResourceManager.GetString("Error_InvalidScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open file {0}!.
        /// </summary>
        internal static string Error_PathOpen {
            get {
                return ResourceManager.GetString("Error_PathOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML files|*.html.
        /// </summary>
        internal static string MainForm_ExportFileDialog_Filter {
            get {
                return ResourceManager.GetString("MainForm_ExportFileDialog_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheme files|*.jsch.
        /// </summary>
        internal static string MainForm_FileDialog_Filter {
            get {
                return ResourceManager.GetString("MainForm_FileDialog_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logic Simulator.
        /// </summary>
        internal static string MainForm_Name {
            get {
                return ResourceManager.GetString("MainForm_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the current project?.
        /// </summary>
        internal static string MainForm_SaveMessage {
            get {
                return ResourceManager.GetString("MainForm_SaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add elements.
        /// </summary>
        internal static string MainForm_ToolStrip_AddButtonPrompt {
            get {
                return ResourceManager.GetString("MainForm_ToolStrip_AddButtonPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect elements.
        /// </summary>
        internal static string MainForm_ToolStrip_ConnectButtonPrompt {
            get {
                return ResourceManager.GetString("MainForm_ToolStrip_ConnectButtonPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete elements.
        /// </summary>
        internal static string MainForm_ToolStrip_DeleteButtonPrompt {
            get {
                return ResourceManager.GetString("MainForm_ToolStrip_DeleteButtonPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move elements.
        /// </summary>
        internal static string MainForm_ToolStrip_MoveButtonPrompt {
            get {
                return ResourceManager.GetString("MainForm_ToolStrip_MoveButtonPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string Menu_Context_Element_Connect {
            get {
                return ResourceManager.GetString("Menu_Context_Element_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Menu_Context_Element_Delete {
            get {
                return ResourceManager.GetString("Menu_Context_Element_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        internal static string Menu_Context_Element_Move {
            get {
                return ResourceManager.GetString("Menu_Context_Element_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string Menu_Context_Element_Rename {
            get {
                return ResourceManager.GetString("Menu_Context_Element_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all.
        /// </summary>
        internal static string Menu_Context_Scheme_ClearAll {
            get {
                return ResourceManager.GetString("Menu_Context_Scheme_ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string Menu_Main_File {
            get {
                return ResourceManager.GetString("Menu_Main_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export as HTML.
        /// </summary>
        internal static string Menu_Main_File_Export {
            get {
                return ResourceManager.GetString("Menu_Main_File_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string Menu_Main_File_New {
            get {
                return ResourceManager.GetString("Menu_Main_File_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Menu_Main_File_Open {
            get {
                return ResourceManager.GetString("Menu_Main_File_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string Menu_Main_File_Print {
            get {
                return ResourceManager.GetString("Menu_Main_File_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Menu_Main_File_Save {
            get {
                return ResourceManager.GetString("Menu_Main_File_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        internal static string Menu_Main_File_SaveAs {
            get {
                return ResourceManager.GetString("Menu_Main_File_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Menu_Main_Help {
            get {
                return ResourceManager.GetString("Menu_Main_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Menu_Main_Help_About {
            get {
                return ResourceManager.GetString("Menu_Main_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string Menu_Main_Tools {
            get {
                return ResourceManager.GetString("Menu_Main_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From equation.
        /// </summary>
        internal static string Menu_Main_Tools_FromEquation {
            get {
                return ResourceManager.GetString("Menu_Main_Tools_FromEquation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time diagram.
        /// </summary>
        internal static string Menu_Main_Tools_GetTimeDiagram {
            get {
                return ResourceManager.GetString("Menu_Main_Tools_GetTimeDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table of values.
        /// </summary>
        internal static string Menu_Main_Tools_GetValuesTable {
            get {
                return ResourceManager.GetString("Menu_Main_Tools_GetValuesTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new name.
        /// </summary>
        internal static string NameDialog_Label {
            get {
                return ResourceManager.GetString("NameDialog_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change name.
        /// </summary>
        internal static string NameDialog_Name {
            get {
                return ResourceManager.GetString("NameDialog_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table of values.
        /// </summary>
        internal static string TableDialog_Name {
            get {
                return ResourceManager.GetString("TableDialog_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input settings.
        /// </summary>
        internal static string TimeDiagramDialog_GroupBoxInputs {
            get {
                return ResourceManager.GetString("TimeDiagramDialog_GroupBoxInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State 0 change time.
        /// </summary>
        internal static string TimeDiagramDialog_Label_State0ChangeTime {
            get {
                return ResourceManager.GetString("TimeDiagramDialog_Label_State0ChangeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State 1 change time.
        /// </summary>
        internal static string TimeDiagramDialog_Label_State1ChangeTime {
            get {
                return ResourceManager.GetString("TimeDiagramDialog_Label_State1ChangeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulation time.
        /// </summary>
        internal static string TimeDiagramDialog_LabelTime {
            get {
                return ResourceManager.GetString("TimeDiagramDialog_LabelTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time diagram.
        /// </summary>
        internal static string TimeDiagramDialog_Name {
            get {
                return ResourceManager.GetString("TimeDiagramDialog_Name", resourceCulture);
            }
        }
    }
}
